//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABC_WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Balance
    {
        public int Balance_ID { get; set; }
        public int Client_ID { get; set; }
        public decimal Balance1 { get; set; }
    }
}
